version: '3.8'
services:
  
  ftn:
    build: ./ftn
    ports:
      - "8000:8000"
  
  pmf:
    build: ./pmf
    ports:
      - "8001:8001"
      
  pravni:
    build: ./pravni
    ports:
      - "8002:8002"

  uns:
    build: ./uns
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
               
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=super_secret
      - POSTGRES_DB=uns_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

