version: '3.8'
services:
  
  ftn:
    #build: ./ftn
    image: piwneuh/ssluzba-cloud-project:ftn
    ports:
      - "8000:8000"
  
  pmf:
    #build: ./pmf
    image: piwneuh/ssluzba-cloud-project:pmf
    ports:
      - "8001:8001"
      
  pravni:
    #build: ./pravni
    image: piwneuh/ssluzba-cloud-project:pravni
    ports:
      - "8002:8002"

  uns60:
    #build: ./uns
    image: piwneuh/ssluzba-cloud-project:uns
    restart: always
    ports:
      - "3111:3000"
    depends_on:
      postgres:
        condition: service_healthy
        
  uns40:
    #build: ./uns
    image: piwneuh/ssluzba-cloud-project:uns
    restart: always
    ports:
      - "3222:3000"
    depends_on:
      postgres:
        condition: service_healthy
   
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - uns60
      - uns40
    ports:
      - "80:80"
               
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=super_secret
      - POSTGRES_DB=uns_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
